// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/SlateEditorial.tsx": () => import("../components/mockups/dashboard/SlateEditorial.tsx"),
  "./components/mockups/dashboard/StudioDark.tsx": () => import("../components/mockups/dashboard/StudioDark.tsx"),
  "./components/mockups/dashboard/StudioLight.tsx": () => import("../components/mockups/dashboard/StudioLight.tsx")
};
